### PR TITLE
Fix segfault when reporting error during install

### LINKED ISSUE #3634: Segfault when installing from a toolbox container
## Linux distribution and version
Fedora silverblue 32
## Flatpak version
1.6.3
## Description of the problem
Segfault when installing something from inside a toolbox container.

## Steps to reproduce

From inside a fedora toolbox container, do
```sudo flatpak install org.freedesktop.Sdk.Extension.rust-stable```

## Debugging

```
#0  operation_error (transaction=<optimized out>, op=0x5555557df030, error=0x0, detail=(unknown: 0)) at app/flatpak-cli-transaction.c:478
#1  0x00007ffff6960af0 in ffi_call_unix64 () from /lib64/libffi.so.6
#2  0x00007ffff69602ab in ffi_call () from /lib64/libffi.so.6
#3  0x00007ffff779a89d in g_cclosure_marshal_generic_va () from /lib64/libgobject-2.0.so.0
#4  0x00007ffff7799af6 in _g_closure_invoke_va () from /lib64/libgobject-2.0.so.0
#5  0x00007ffff77b2813 in g_signal_emit_valist () from /lib64/libgobject-2.0.so.0
#6  0x00007ffff77b2d93 in g_signal_emit () from /lib64/libgobject-2.0.so.0
#7  0x000055555564944b in flatpak_transaction_real_run (self=<optimized out>, cancellable=<optimized out>, error=<optimized out>) at common/flatpak-transaction.c:4089
#8  0x00005555555dd41e in flatpak_cli_transaction_run (transaction=0x55555578e100, cancellable=0x0, error=0x7fffffffded8) at ./common/flatpak-transaction.h:92
#9  0x00005555555af58b in flatpak_builtin_install (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=0x7fffffffded8) at app/flatpak-builtins-install.c:525
#10 0x00005555555a5d98 in flatpak_run (res_error=0x7fffffffdec8, argv=<optimized out>, argc=<optimized out>) at app/flatpak-main.c:766
#11 main (argc=<optimized out>, argv=<optimized out>) at app/flatpak-main.c:881
```
 the failing instruction is
```c
msg = g_strdup (error->message);
```
in `operation_error` because error is null.

### PR DESCRIPTION
**Pull request by ineol**
flatpak_dir_install was returning FALSE but leaving error to NULL, which
would crash when printing the error.

Fixes #3634

### CODE REVIEW

File: common/flatpak-dir.c [hunk 1]
```diff
@@ -8707,12 +8707,15 @@ flatpak_dir_install (FlatpakDir          *self,
           if (is_revokefs_pull &&
               !flatpak_dir_revokefs_fuse_unmount (&child_repo, &child_repo_lock, mnt_dir, &local_error))
             {
-              g_warning ("Could not unmount revokefs-fuse filesystem at %s: %s", mnt_dir, local_error->message);
-              flatpak_dir_unmount_and_cancel_pull (self,
-                                                   FLATPAK_HELPER_CANCEL_PULL_FLAGS_PRESERVE_PULL,
-                                                   cancellable,
-                                                   &child_repo, &child_repo_lock,
-                                                   mnt_dir, src_dir);
+              g_propagate_prefixed_error(error, g_steal_pointer (&local_error),
```
Comment (TingPing) [inline common/flatpak-dir.c:8710]:
```suggestion
              g_propagate_prefixed_error (error, g_steal_pointer (&local_error), 
```

Comment (ineol) [reply common/flatpak-dir.c]: Fixed, thanks

File: app/flatpak-cli-transaction.c [hunk 2]
```diff
@@ -473,8 +473,10 @@ operation_error (FlatpakTransaction            *transaction,
     msg = g_strdup_printf (_("%s needs a later flatpak version"), flatpak_ref_get_name (rref));
   else if (g_error_matches (error, FLATPAK_ERROR, FLATPAK_ERROR_OUT_OF_SPACE))
     msg = g_strdup (_("Not enough disk space to complete this operation"));
-  else
+  else if (error)
     msg = g_strdup (error->message);
+  else
+    msg = g_strdup ("(internal error, please report)");
```
Comment (alexlarsson) [inline app/flatpak-cli-transaction.c:479]: This should be translated (i.e. `_("(inter..")`)

File: common/flatpak-dir.c [hunk 3]
```diff
@@ -8707,12 +8707,15 @@ flatpak_dir_install (FlatpakDir          *self,
...
               !flatpak_dir_revokefs_fuse_unmount (&child_repo, &child_repo_lock, mnt_dir, &local_error))
             {
-              g_warning ("Could not unmount revokefs-fuse filesystem at %s: %s", mnt_dir, local_error->message);
-              flatpak_dir_unmount_and_cancel_pull (self,
-                                                   FLATPAK_HELPER_CANCEL_PULL_FLAGS_PRESERVE_PULL,
-                                                   cancellable,
-                                                   &child_repo, &child_repo_lock,
-                                                   mnt_dir, src_dir);
+              g_propagate_prefixed_error (error, g_steal_pointer (&local_error), 
+                      "Could not unmount revokefs-fuse filesystem at %s: ", mnt_dir);
```
Comment (alexlarsson) [inline common/flatpak-dir.c:8711]: Needs translation here too
