### PR TITLE
Make /dev/shm shareable between app instances

### LINKED ISSUE #4091: RFE: subsandboxes that can share /dev/shm, /tmp with main app, but not host
## Linux distribution and version

any

## Flatpak version

1.10.1

## Description of the problem

If an app creates a subsandbox (as Steam will want to do for #3797), the main app and each subsandbox get their own instance of `/tmp` (a separate tmpfs), unless the app has the `--filesystem=/tmp` permission, which would weaken the sandboxing.

Similarly, the main app and each subsandbox get their own instance of `/dev/shm`, unless the app has the `--device=shm` permission.

This is a problem because `/tmp` and `/dev/shm` are among the few locations that portable programs can use for IPC:

* `$XDG_RUNTIME_DIR` doesn't exist on systems that don't have systemd-logind, elogind or something similar
* `$HOME` and `$XDG_CACHE_HOME` might be too long to put proper namespacing/uniqueness in an `AF_UNIX` socket name (which are limited to 108 bytes)
* `$HOME` and `$XDG_CACHE_HOME` might be on NFS, SMB/CIFS or some other not-quite-POSIX filesystem that cannot accommodate `AF_UNIX` sockets or the standard trick of using an unlinked file as an anonymous memory buffer
* `$HOME` and `$XDG_CACHE_HOME` might be on NFS, SMB/CIFS or something else that is slow
* as implemented in glibc, POSIX shared memory (`shm_open(3)`) always uses `/dev/shm/` and cannot be redirected elsewhere

and it is reasonable for a subsandboxed program to want to communicate with the main app that initiated the sandbox.

For example, Steam creates a socket `/tmp/steam_chrome_overlay_${something}`, which game processes use to render HTML in the Steam Overlay. Steam also uses POSIX shm (`shm_open(3)`) or some other mechanism involving `/dev/shm`, although I don't know precisely what that's used for.

Prior to #3797, all Steam components and Steam games in a Flatpak'd Steam ran in the same `bwrap` instance, so they automatically and transparently all had the same `/tmp` and `/dev/shm`; but when we start putting games and possibly other components into subsandboxes, for them to continue to communicate, they should be able to share `/tmp` and `/dev/shm`.

## Steps to reproduce

```
host$ flatpak run --command=bash --nofilesystem=/tmp --nodevice=shm ${any_app}
[📦 app ~]$ touch /tmp/THIS_IS_MY_PRIVATE_TMP
[📦 app ~]$ touch /dev/shm/THIS_IS_MY_PRIVATE_DEV_SHM
[📦 app ~]$ flatpak-spawn ls /tmp
(nothing listed)
[📦 app ~]$ flatpak-spawn ls /dev/shm
(nothing listed)
```

The desired result is that the subsandbox's `/tmp` is the same directory as the app's `/tmp` (demonstrated by it containing the flag-file `THIS_IS_MY_PRIVATE_TMP`), or that there is some option on the app and/or flatpak-spawn that can be used to make that happen; and the same for `/dev/shm`.

## Workaround

If the app is given the `--filesystem=/tmp` permission, then it will share the host's `/tmp`, and the subsandboxes will also share the host's `/tmp`. By transitivity, this ends up with the app and the subsandboxes having the same `/tmp`. However, this is an undesirable exposure of host files, such as temporary downloaded files in `/tmp/mozilla*`, in the sandbox.

The same is true for `/dev/shm` and `--device=shm`.

### PR DESCRIPTION
**Pull request by smcv**
Fixes #4091.

## Design

The interesting subset of the host filesystem is now:

```
real host g_get_user_runtime_dir()
    \- app
        \- com.example.App (gets mounted as XDG_RUNTIME_DIR/app/com.example.App as before)
    \- .flatpak
        \- 123 (instance-specific directory, already used)
        \- 456 (instance-specific directory, already used)
        \- com.example.App (per-app directory, new in #4093)
            \- .ref (locked non-exclusively by app, new in #4093)
            \- tmp (gets mounted as /tmp in app sandbox, new in #4093)
            \- dev-shm (symlink to /dev/shm/flatpak-com.example.App-abcdef, new)

real host /dev/shm
    \- flatpak-com.example.App-abcdef (or similar unpredictable name, new)
        \- .flatpak-tmpdir
```

As with #4093, the shared `/dev/shm` is only used for `flatpak run`, not for `flatpak build` (which reinvents a lot of `flatpak_run_app()`), and also not for `apply_extra`.

Whenever we garbage-collect the numbered per-instance directories, we check their app info. If an instance is disappearing, we attempt to garbage-collect the corresponding `dev-shm` if no apps are still using it. The shared `/dev/shm` is currently backed by a directory `/dev/shm/flatpak-com.example.App-XXXXXX`, so that it's basically guaranteed to be genuinely a tmpfs.

The format of the temporary directory `/dev/shm/flatpak-com.example.App-XXXXXX` is checked, to defend against being tricked into deleting a directory that we didn't mean to. The app name is included in the directory name, so that if an app uses an excessive amount of space, users can blame the app and not Flatpak itself.

The flag file `.flatpak-tmpdir` is also checked for, again as a safety-catch against deleting unintended directories. This is loosely based on the `.testtmp` used in the libostree and Flatpak unit tests.

Having a shared `/dev/shm` is guarded by a feature flag as @alexlarsson requested: we don't expect so many apps to need this.

## Commits

* run: Add option to share /dev/shm between instances of an app-ID
    
    Similar to /tmp, applications might well use /dev/shm as an IPC
    rendezvous between instances, which wouldn't have worked without
    --device=shm until now.
    
    Because /dev/shm has specific characteristics (in particular it's
    meant to always be a tmpfs), we offload the actual storage into a
    subdirectory of the real /dev/shm. Because /dev/shm is a shared
    directory between all uids, we have to be extra-careful how we
    do this, which is why the test coverage here is important.
    
    This is done on an opt-in basis because of its extra complexity.

### CODE REVIEW

File: common/flatpak-instance.c [hunk 1]
```diff
@@ -641,6 +762,147 @@ flatpak_instance_new_for_id (const char *id)
...
+ * failing when an unexpected situation is detected.
+ *
+ * @error is not normally user-visible, and is mostly present to support
+ * debugging and unit testing.
+ *
+ * Returns: %TRUE if @link_path points to a suitable directory,
+ *  or %FALSE with @error set if it does not.
+ */
+gboolean
+flatpak_instance_claim_per_app_temp_directory (const char *app_id,
```
Comment (smcv) [inline common/flatpak-instance.c:798]: As with this function's earlier existence in #4093, it's security-sensitive, so please review carefully.

I added test coverage for all the branches except `fstat()` failing (which I don't know how to trigger on-demand). To get full test coverage for it, you need to run tests as non-root, and pre-create `/tmp/flatpak-com.example.App-OwnedByRoot` owned by root (which I'm going to try to add to the CI).

File: common/flatpak-instance.c [hunk 2]
```diff
@@ -720,6 +982,63 @@ flatpak_instance_gc_per_app_dirs (const char *instance_id,
...
+                                                         "dev-shm",
+                                                         "/dev/shm",
+                                                         F_WRLCK,
+                                                         &lock_fd,
+                                                         &path,
+                                                         &local_error))
+        {
+          g_assert (g_str_has_prefix (path, "/dev/shm/"));
+
+          if (!glnx_shutil_rm_rf_at (AT_FDCWD, path, NULL, &local_error))
```
Comment (alexlarsson) [inline common/flatpak-instance.c:1012]: There seems to be a race condition here where someone could potentially reuse the directory in the middle of the rm, if the lock file is removed. You could make this atomic (ish) by renaming the directory before starting to remove it.

File: common/flatpak-run.c [hunk 3]
```diff
@@ -1400,10 +1400,44 @@ flatpak_run_add_environment_args (FlatpakBwrap    *bwrap,
...
+               * flatpak-spawn --sandbox, which will have their own). */
+              if (!flatpak_instance_ensure_per_app_dev_shm (app_id,
+                                                            per_app_dir_lock_fd,
+                                                            &dev_shm_lock_fd,
+                                                            &shared_dev_shm,
+                                                            error))
+                return FALSE;
+
+              /* Hold the lock until we execute bwrap */
+              flatpak_bwrap_add_fd (bwrap, glnx_steal_fd (&dev_shm_lock_fd));
```
Comment (alexlarsson) [inline common/flatpak-run.c:1427]: I think this should be a flatpak_bwrap_add_noinherit_fd() call, there is no need to pass this actual into the child process.

File: common/flatpak-run.c [hunk 4]
```diff
@@ -1415,13 +1449,39 @@ flatpak_run_add_environment_args (FlatpakBwrap    *bwrap,
...
+                   * but we want other instances to be able to share /dev/shm,
+                   * except for flatpak-spawn --subsandbox. */
+                  if (!flatpak_instance_ensure_per_app_dev_shm (app_id,
+                                                                per_app_dir_lock_fd,
+                                                                &dev_shm_lock_fd,
+                                                                &shared_dev_shm,
+                                                                error))
+                    return FALSE;
+
+                  flatpak_bwrap_add_fd (bwrap, glnx_steal_fd (&dev_shm_lock_fd));
```
Comment (alexlarsson) [inline common/flatpak-run.c:1473]: same here.

File: common/flatpak-run.c [hunk 5]
```diff
@@ -1483,8 +1543,26 @@ flatpak_run_add_environment_args (FlatpakBwrap    *bwrap,
...
+          g_autofree char *shared_dev_shm = NULL;
+
+          if (!flatpak_instance_ensure_per_app_dev_shm (app_id,
+                                                        per_app_dir_lock_fd,
+                                                        &dev_shm_lock_fd,
+                                                        &shared_dev_shm,
+                                                        error))
+            return FALSE;
 
+          flatpak_bwrap_add_fd (bwrap, glnx_steal_fd (&dev_shm_lock_fd));
```
Comment (alexlarsson) [inline common/flatpak-run.c:1559]: and here

File: common/flatpak-instance.c (hunk 2 above)
Comment (smcv) [reply common/flatpak-instance.c:1012]: Thanks, I'll look into this. I think it *might* actually be OK, but it's certainly subtle, and I might have missed something.

I'm really starting to think that a lock file in a directory that protects that directory is an anti-pattern, which is why I stopped using it for #4093.

Comment (smcv) [reply common/flatpak-instance.c:1012]: Sorry, no, I considered stopping using the lock-file-in-directory pattern in #4093 (one version had `.flatpak/.ref-com.example.App` and `.flatpak/com.example.App/`), but in the end I'm still using it there, and I address the race condition by just not deleting the directory or the lock file.

Comment (smcv) [reply common/flatpak-instance.c:1012]: I think this isn't actually a problem, for two orthogonal reasons (but I've fixed some different issues while I was looking at this).

The first reason it can't happen in practice is that because by the time we work with the `dev-shm` symlink, we are already holding a lock on `$XDG_RUNTIME_DIR/.flatpak/$FLATPAK_ID/.ref` (which we never delete). Because we check that the directory in `/dev/shm` has the `$FLATPAK_ID` in its name, we can know that we're holding the correct lock to exclude other processes that might be interested in it. We hold an exclusive lock (`F_WRLCK`) if we are considering deleting things, or a non-exclusive lock that conflicts with exclusive locks (`F_RDLCK`) otherwise.

However, even if that wasn't the case, I think the way we work with `.flatpak-tmpdir` would be enough to avoid the problem. The places where we take a lock on `.flatpak-tmpdir` are:

* `flatpak_instance_ensure_per_app_dev_shm()` when it creates a new directory
* `flatpak_instance_claim_per_app_temp_directory()` called by `flatpak_instance_ensure_per_app_dev_shm()` when it reuses an existing directory
* `flatpak_instance_claim_per_app_temp_directory()` called by `flatpak_instance_gc_per_app_dirs()` when it removes an existing directory

In the "newly created" code path of `flatpak_instance_ensure_per_app_dev_shm()`, the directory containing `.flatpak-tmpdir` is newly-created by `g_mkdtemp()`, so we can only be racing with another process in the very unlikely situation where `g_mkdtemp()` coincidentally gives us a directory name that matches a pre-existing symlink in `$XDG_RUNTIME_DIR`. This is also the only place where we use `O_CREAT` to create a new lock file. Ideally I would have used `O_EXCL` and `O_NOFOLLOW` here; I've added those, and also `O_NOCTTY`, for completeness.

In both the `flatpak_instance_claim_per_app_temp_directory()` code paths, we open the lock file without `O_CREAT`, so we will only open it successfully if the lock file was already created for us. I was missing `O_NOFOLLOW` here, which is potentially a problem, because a malicious app could delete the lock file and replace it with a symlink, which we would follow and (briefly) lock the target of - but this is mitigated by the fact that we are not using `O_CREAT`, so we will not create new empty files, just open existing files. Anyway, I've added that now (along with `O_NOCTTY` for completeness).

Your concern was about deletion. There are two things that could conceivably race with deleting the directory:

1. trying to reuse an existing directory
2. creating a new directory, with `g_mkdtemp()` coincidentally giving us the same directory we used before (again, unlikely but possible!)

Looking at scenario 1, where we are trying to reuse an existing directory, then both the processes that are racing will try to open `.flatpak-tmpdir` without `O_CREAT`. The process that tries to reuse the directory can either call `openat()` before `glnx_shutil_rm_rf_at()` unlinks `.flatpak-tmpdir`, or after.

If it's before, then both the processes involved in the race will have the same file open, and their locks conflict, so one of them will fail to get the lock and we're OK: if the process that wants to reuse the directory wins, then it is allowed to reuse the directory and GC does not happen. Conversely, if the process that wants to GC the directory wins, then it is allowed to delete the directory, and the other process will fail to reuse it (and recover by making a new directory instead).

If it's after, then the process that is trying to reuse the directory will have its call to `openat()` fail, and will not reuse the directory: instead it will create a new directory, the same as if it lost the race to get a lock. So we're OK either way.

Now scenario 2, where we are trying to create a new directory. `g_mkdtemp()` is basically going to end up as a retry loop, trying to `mkdir()` a new, unique directory matching `/dev/shm/flatpak-$FLATPAK_ID-XXXXXX` for some value of `XXXXXX`. Let's say it generates `/dev/shm/flatpak-$FLATPAK_ID-123456`, and let's say it's racing with a process that is calling `glnx_shutil_rm_rf_at()` on `/dev/shm/flatpak-$FLATPAK_ID-123456`, which basically means `unlink ("/dev/shm/flatpak-$FLATPAK_ID-123456/.flatpak-tmpdir")` followed by `rmdir ("/dev/shm/flatpak-$FLATPAK_ID-123456")`. Either `mkdir` happens before `rmdir`, or it happens after.

If `mkdir` happens before `rmdir`, then the `mkdir` fails with `EEXIST`, and `g_mkdtemp()` will retry with a different directory name, so we're OK.

If `rmdir` happens before `mkdir`, then GC has (basically) completely finished by the time `mkdir` gets called, so it's as though there was no race: GC finishes before reuse starts. The only thing that could still go wrong is that GC had not *100%* finished: I was using `unlinkat()` to clean up the symlink `$XDG_RUNTIME_DIR/.flatpak/$FLATPAK_ID/dev-shm` *after* deleting the directory that it points to. I've now changed the sequence so that I do the `unlinkat()` first.

Comment (smcv) [reply common/flatpak-instance.c:1012]: To make this more obviously correct, I'm going to remove the extra locking and just rely on the per-app-ID lock file.

File: common/flatpak-run.c (hunk 3 above)
Comment (smcv) [reply common/flatpak-run.c]: In the latest revision this lock fd has gone away entirely (I've simplified to just relying on the per-app-ID lock) so this code is no longer present.

File: common/flatpak-instance.c (hunk 2 above)
Comment (smcv) [reply common/flatpak-instance.c:982]: OK, new version seems to work. Now `.flatpak-tmpdir` is just a flag file to say "this is probably OK to delete", and not a lock.

Concurrent processes are guarded against by the per-app-ID lock file `$XDG_RUNTIME_DIR/.flatpak/$FLATPAK_ID/.ref`. Running apps hold a non-exclusive (read) lock, waiting for it to be available if necessary. Garbage collection takes an exclusive (write) lock, and does not wait.
