### PR TITLE
permission-reset: Avoid setting unchanged table entries

### LINKED ISSUE #5772: [Bug]: flatpak permission-reset takes very long
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

f40

### What architecture are you using?

x86_64

### How to reproduce

Running
```
flatpak permission-reset org.gnome.Snapshot
```

### Expected Behavior

Takes less than 1s.

### Actual Behavior

Takes around 5s.

### Additional Information

In the journal I only see
```
abr 11 20:39:39 thinkpad polkitd[1156]: Registered Authentication Agent for unix-process:124813:52425856 (system bus name :1.1239 [flatpak permission-reset org.gnome.Snapshot], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
abr 11 20:39:43 thinkpad polkitd[1156]: Unregistered Authentication Agent for unix-process:124813:52425856 (system bus name :1.1239, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
```

### PR DESCRIPTION
**Pull request by chrisawi**
This reduces the best case (no-op) execution time from ~900 ms to <100 ms on my system.

Closes #5772

### CODE REVIEW

File: app/flatpak-builtins-permission-reset.c [hunk 1]
```diff
@@ -69,6 +69,7 @@ remove_for_app (XdpDbusPermissionStore *store,
       char *key;
       GVariant *value;
       GVariantBuilder builder;
```
Comment (swick) [inline app/flatpak-builtins-permission-reset.c:71]:
```suggestion
      g_auto(GVariantBuilder) builder = FLATPAK_VARIANT_BUILDER_INITIALIZER;
```
and get rid of the manual cleanup

**Comment by swick** [comment]
LGTM otherwise

File: app/flatpak-builtins-permission-reset.c (hunk 1 above)
Comment (chrisawi) [reply app/flatpak-builtins-permission-reset.c]: Done, thanks

File: app/flatpak-builtins-permission-reset.c [hunk 2]
```diff
@@ -81,16 +82,20 @@ remove_for_app (XdpDbusPermissionStore *store,
...
-                                                    g_variant_builder_end (&builder),
-                                                    data ? data : g_variant_new_byte (0),
-                                                    NULL, error))
-        return FALSE;
+      if (need_to_set)
+        if (!xdp_dbus_permission_store_call_set_sync (store, table, TRUE, ids[i],
+                                                      g_variant_builder_end (&builder),
+                                                      data ? data : g_variant_new_byte (0),
+                                                      NULL, error))
+          return FALSE;
```
Comment (swick) [inline app/flatpak-builtins-permission-reset.c:98]:
```suggestion
      if (need_to_set)
        {
          if (!xdp_dbus_permission_store_call_set_sync (store, table, TRUE, ids[i],
                                                        g_variant_builder_end (&builder),
                                                        data ? data : g_variant_new_byte (0),
                                                        NULL, error))
            return FALSE;
        }
```
